### ISSUE TITLE
The example does not work build with the latest version of the SDK

### ISSUE THREAD

**Issue by vijaytholpadi** [OmniVirt/OmniVirtVRPlayer-iOS-Example#2]
The example is currently using v1.2.1 (Both Swift and ObjC)

The Example app is no indication of how any of the newer versions of the SDK has to be used.

Kindly update.

**Comment by nuuneoi** [comment]
Dear Vijay,

Thanks a ton for reporting this. It appears that problem has been there because some big change Apple made with Swift 4. We just updated the SDK to fix the problem and it should now work with Objective-C code. Please kindly check if everything is good now!

![screenshot 2018-10-11 09 08 43](https://user-images.githubusercontent.com/61659/46776413-a0d3dc80-cd35-11e8-8d97-ca1129afdfc5.jpg)

**Comment by vijaytholpadi** [comment]
@nuuneoi You're welcome. Thanks for looking into this. Much appreciated!
